import { Link } from "react-router-dom";
import {
  FileText,
  Scale,
  Ban,
  ServerCrash,
  RefreshCw,
  Mail,
  ShieldAlert,
  Users,
} from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SEO from "@/components/SEO";

const termsSections = [
  {
    icon: FileText,
    title: "Acceptance of Terms",
    id: "acceptance",
    points: [
      "By downloading, installing, or using Spark, you agree to be bound by these Terms of Service.",
      "If you do not agree to these terms, do not install or use the application.",
      "These terms apply to all users of the Spark desktop application and its associated website at spark-app.in.",
    ],
  },
  {
    icon: Scale,
    title: "License to Use",
    id: "license",
    points: [
      "Spark grants you a personal, non-exclusive, non-transferable, revocable license to use the application for your own personal and professional productivity.",
      "This license does not include the right to resell, redistribute, sublicense, or commercially exploit the software.",
      "You may install Spark on any number of Windows devices that you personally own or control.",
      "The source code, design, and underlying intellectual property remain the sole property of the Spark team.",
    ],
  },
  {
    icon: Ban,
    title: "Prohibited Uses",
    id: "prohibited",
    points: [
      "You may not use Spark to generate, transmit, or store content that is unlawful, harmful, abusive, harassing, defamatory, or otherwise objectionable.",
      "You may not attempt to reverse-engineer, decompile, or disassemble Spark or its components.",
      "You may not use Spark as part of an automated system, bot, or scraping pipeline at scale without prior written consent.",
      "You may not impersonate Spark or misrepresent your affiliation with the application.",
    ],
  },
  {
    icon: Users,
    title: "Third-Party Services",
    id: "third-party",
    points: [
      "Spark integrates with third-party AI providers such as Groq and OpenRouter. Your use of those services is governed by their respective terms and privacy policies.",
      "You are solely responsible for obtaining and managing valid API keys for third-party providers.",
      "Spark does not endorse, warrant, or assume liability for the outputs generated by third-party AI models.",
      "Third-party service availability or pricing changes are outside Spark's control.",
    ],
  },
  {
    icon: ShieldAlert,
    title: "Disclaimers",
    id: "disclaimers",
    points: [
      'Spark is provided "as is" and "as available" without warranty of any kind, express or implied.',
      "We do not warrant that Spark will be uninterrupted, error-free, or free of malicious code.",
      "AI-generated output may be inaccurate, incomplete, or inappropriate. Always review results before use.",
      "Spark is not responsible for any decisions made based on AI-generated content produced through the application.",
    ],
  },
  {
    icon: ServerCrash,
    title: "Limitation of Liability",
    id: "liability",
    points: [
      "To the fullest extent permitted by law, Spark and its contributors shall not be liable for any indirect, incidental, special, or consequential damages.",
      "This includes but is not limited to loss of data, lost profits, goodwill, or business interruption arising from your use of the application.",
      "Our total aggregate liability in any situation is limited to the amount you paid for Spark (if any) in the twelve months preceding the claim.",
    ],
  },
  {
    icon: RefreshCw,
    title: "Changes to These Terms",
    id: "changes",
    points: [
      "We reserve the right to update these Terms of Service at any time. Continued use of Spark after changes constitutes acceptance of the revised terms.",
      "Material changes will be communicated through the developer notifications system built into the app.",
      "The date of the latest revision is shown at the bottom of this page.",
    ],
  },
  {
    icon: Mail,
    title: "Contact",
    id: "contact",
    points: [
      "For questions about these terms, please contact us at akhil.builds@proton.me or through the Issues page.",
      "Legal notices must be submitted in writing and will receive a response within a reasonable timeframe.",
    ],
  },
];

const Terms = () => {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <SEO
        title="Spark Terms of Service"
        description="Read the Spark Terms of Service to understand license terms, prohibited uses, disclaimers, and your rights when using the Spark Windows AI text assistant."
        path="/terms"
      />
      <Navbar />

      <main className="relative pt-28 md:pt-36 pb-16 md:pb-24 overflow-hidden">
        {/* Background glow */}
        <div className="absolute inset-0 -z-10">
          <div className="absolute top-0 left-1/2 -translate-x-1/2 h-72 w-[36rem] rounded-full bg-primary/10 blur-[110px]" />
        </div>

        <div className="container max-w-4xl mx-auto px-6">
          {/* Header */}
          <div className="text-center mb-12 md:mb-14">
            <p className="inline-flex items-center rounded-full border border-border bg-card/80 px-3 py-1 text-xs tracking-wide text-muted-foreground">
              Legal
            </p>
            <h1 className="mt-4 text-4xl md:text-5xl font-bold tracking-[-0.03em] text-gradient">
              Terms of Service
            </h1>
            <p className="mt-4 text-muted-foreground max-w-2xl mx-auto leading-relaxed">
              Please read these terms carefully before using Spark. By using the
              app you agree to be bound by the conditions described here.
            </p>
            <p className="mt-2 text-sm text-muted-foreground">
              Last updated: March 18, 2026
            </p>
          </div>

          {/* Quick nav */}
          <div className="mb-10 rounded-2xl border border-border/60 bg-card/60 p-5">
            <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-3">
              Jump to section
            </p>
            <div className="flex flex-wrap gap-2">
              {termsSections.map((s) => (
                <a
                  key={s.id}
                  href={`#${s.id}`}
                  className="text-xs px-3 py-1.5 rounded-lg bg-secondary hover:bg-secondary/70 text-muted-foreground hover:text-foreground transition-colors"
                >
                  {s.title}
                </a>
              ))}
            </div>
          </div>

          {/* Sections */}
          <div className="space-y-6">
            {termsSections.map((section) => {
              const Icon = section.icon;
              return (
                <section
                  key={section.id}
                  id={section.id}
                  className="rounded-2xl border border-border/70 bg-card/80 backdrop-blur-sm p-6 md:p-7 shadow-card scroll-mt-24"
                >
                  <div className="flex items-center gap-3 mb-4">
                    <div className="h-9 w-9 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0">
                      <Icon className="h-4 w-4" />
                    </div>
                    <h2 className="text-xl font-semibold tracking-tight">
                      {section.title}
                    </h2>
                  </div>
                  <ul className="space-y-3 text-muted-foreground leading-relaxed">
                    {section.points.map((point) => (
                      <li key={point} className="flex items-start gap-3">
                        <span className="mt-2 h-1.5 w-1.5 rounded-full bg-primary/60 shrink-0" />
                        <span>{point}</span>
                      </li>
                    ))}
                  </ul>
                </section>
              );
            })}
          </div>

          {/* Footer links */}
          <div className="mt-10 flex flex-col sm:flex-row items-center gap-3 justify-center">
            <Link
              to="/"
              className="inline-flex items-center rounded-xl bg-secondary hover:bg-secondary/80 px-4 py-2.5 text-sm font-medium transition-colors"
            >
              Back to Home
            </Link>
            <Link
              to="/privacy-policy"
              className="inline-flex items-center rounded-xl border border-border/60 hover:bg-card px-4 py-2.5 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
            >
              Privacy Policy
            </Link>
            <Link
              to="/issues"
              className="inline-flex items-center rounded-xl border border-border/60 hover:bg-card px-4 py-2.5 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
            >
              Contact via Issues
            </Link>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Terms;
